womenemp/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.user_login,name='login'),
    path('reg/',views.reg,name='reg'),
    path('ticket-book/',views.ticket_book,name='ticket-book'),
    path('payment/',views.payment,name='payment'),
    path('userpro/',views.userprofile,name='userpro'),
    path('admindash/',views.admin,name='admin'),
    path('bus/',views.bus,name='bus'),
    path('house/',views.house,name='house'),
    path('revenue/',views.revenue,name='revenue'),
    path('admlogin/',views.user_login1,name='log'),
]

womenemp/ticket/urls.py
from django.urls import path
from . import views
app_name = 'ticket'
urlpatterns = [
   # path('',views.ticket_book,name='ticket-book'),
]

womenemp/womenemp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('ticket.urls')),
    ]

womenemp/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    
    Women = 'W'


    desginations_choice = [
        ( Women,'Women'),
    ]
    designation = models.CharField(max_length=1,choices=desginations_choice,default=Women)
    phone = models.CharField(max_length=10,null=True,blank=True)
    db_table = 'User'
   
    def __str__(self):
        return self.username

 
class Caterer(models.Model):
    community_name=models.CharField(max_length=255)
    phoneno=models.CharField(max_length=10)
    username=models.CharField(max_length=50)
    password=models.CharField(max_length=50)
    contract_period=models.IntegerField(max_length=2)

womenemp/ticket/models.py
from django.db import models
from accounts.models import User
# Create your models here.
'''class Ticket(models.Model):
    TIME_SLOT = [
    (1, '9:00'),
    (2, '11:00'),
    (3, '1:00'),
    (4, '3:00'),
    (5, '5:00'),
    (6, '7:00'),
    (7, '9:00'),
    ]
    women = models.ForeignKey(User,on_delete=models.CASCADE,limit_choices_to={'user_type': 'W'}, related_name='Women')
    date =  models.DateField()
    slot = models.TimeField(max_length=1,choices=TIME_SLOT)
    status = models.BooleanField(default=False)

    class Meta:
        db_table = 'ticket'
        constraints = [
            models.UniqueConstraint(fields=['women','date'], name='unique_booking')
        ]
        

    def __str__(self):
        return f"{self.women.get_full_name()}'sbooking on {self.women.time} on {self.date}"'''

womenemp/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
class SignUpForm(UserCreationForm):
    class Meta:
        fields = ('username','email','first_name','last_name','password1','password2','designation')
        widgets = {
            'designation':forms.RadioSelect,
        }
        model = User

womenemp/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .forms import SignUpForm
# Create your views here.
def home(request):
    return render(request,'index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,'Login Successful')
            return render(request,'index2.html')
        else:
            messages.error(request,'Invalid Credentials')
            return render(request,'log.html')
    return render(request,'log.html')
    

def reg(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            messages.add_message(request, messages.INFO, f'Welcome {user.get_full_name()}!!!Your account has been registered successfully.')
            return render(request,'index2.html')
    else:
        form = SignUpForm()
    return render(request,'reg.html',{'form':form})

def ticket_book(request):
    return render(request,'ticketbook.html')
def payment(request):
    return render(request,'payment.html')
def userprofile(request):
    return render(request,'user.html')
def admin(request):
    return render(request,'admin.html')
def bus(request):
    return render(request,'buses.html')
def house(request):
    return render(request,'housewife.html')
def revenue(request):
    return render(request,'revenue.html')

def user_login1(request):
    return render(request,'login.html')

womenemp/ticket/views.py
from django.shortcuts import render
# from ticket.models import Ticket
from django.db import connection, IntegrityError
from django.contrib import messages
from accounts.models import User
from django.shortcuts import redirect
from django.http import HttpResponse

# Create your views here.
'''def ticket_book(request,*args):
    if request.method == 'POST':
        context = {}
        women = request.POST['women']
        slot = request.POST['slot']
        date = request.POST['date']
        women_id = User.objects.get(pk=women)
    
    try:
        ticket = Ticket.objects.create(
        women=women_id,
        date = date,
        slot = slot,
        status=False,
        )
    except IntegrityError:
        messages.add_message(request, messages.ERROR, f'Already booked ticket on {date}!')
        return redirect('accounts:index')
        
    context = {'ticket':ticket}
    messages.add_message(request, messages.INFO, f'Booking Successful!')
    return redirect("accounts:home")'''
    

womenemp/accounts/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Mind Empowered</title>
    </head>
    <body>
        <h1>
            <center>WELCOME TO WOMEN EMPOWERMENT SUPPORT SYSTEM</center>
        </h1>
        <br><br>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
        {% for message in messages %}
                <div class="container-fluid p-0">
                  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="True">&times;</span>
                    </button>
                    {{ message }}
                  </div>
                </div>
                {% endfor %}
        <center><a href="{% url 'accounts:login' %}">  <input type="button" value="Login"></a>&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts:reg' %}"><input type="button" value="Register"></a></center>
    </body>
</html>

womenemp/accounts/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>LOGIN</title>
    </head>
    <body>
        <h1>
            <center>LOGIN</center>
        </h1>
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            <table align="center">
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
                <div class="container-fluid p-0 fluid" id="msg">
                    {% for message in messages %}
                      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                      </div>
                    {% endfor %}
                    </div>
                    
                    <script>
                        setTimeout(function(){
                            $(".alert").alert('close')
                        }, 4000);
                        setTimeout(function(){
                            $("#msg").remove();
                        }, 4500);
                    
                    </script>
                    
           
            

               
                <tr>
                    <td>Username:</td>
                    <td><input type="text" name="username"></td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td><input type="password" name="password"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><a href="{% url 'accounts:admin' %}"><input type="submit" value="Login"></a></td>
                </tr>
            </table>
        </form>
    </body>
</html>

womenemp/accounts/templates/reg.html
        

<!--Register--> 
<div class="container py-5" style="width: 95%; font-size:14px">
	<h1>Register</h1>
	<form method="POST" class="card p-3 mt-5" autocomplete="off">
		{% csrf_token %}
		{{ form }}       <!-- All the form's fields and their attributes will be unpacked into HTML markup from that {{form}} by DTL-->             
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'accounts:login' %}">login</a> instead.</p>
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
                {% for message in messages %}
                <div class="container-fluid p-0">
                  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="True">&times;</span>
                    </button>
                    {{ message }}
                  </div>
                </div>
                {% endfor %}

womenemp/ticket/templates/ticket.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <center>WELCOME TO SHE BUS</center>
        <p>
            <!-- <form method="post" action="{% url 'ticket:ticket_book' %}">
                {% csrf_token %}
                <input type="hidden" name="women" value="{{User.id}}">
           Name: <input type="text" name="name">
           {% for i in TIME_SLOT %}
           Select slot: 
           <div class="btn btn-warning">
            <input type="radio" name="slot" id="slot{{forloop.counter}}" required value="{{slot}}">{{slot}}
          </div>
           {% endfor %}
           Select trip: <input type="text" name="trip"> -->
        </p>
    </body>
</html>